server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: Passw0rd
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false